### ISSUE TITLE
Cant get it to work -> Attribute Errors

### ISSUE THREAD

**Issue by ThisisDennis** [Daenara/rhasspy_weather#14]
Im trying to install it on my System, i have no idea how to add Skills to "Rhasspy-Hermes-App" mabye i missed some introduction...
So i tried to build it as a individual service.
But it seems like the intent_message is structured differently, i always get "Attribute Errors". After fixing some, it's too much work, maybe you have an idea, how i get it work without that much effort.
I use Rhasspy Version 2.5.9.

Thank you 
ps.: The message
`slots=[Slot(entity='rhasspy_weather/named_days', value={'kind': 'Unknown', 'value': 'heute'}, slot_name='when_day', raw_value='heute', confidence=1.0, range=SlotRange(start=12, end=17, raw_start=12, raw_end=17)), Slot(entity='rhasspy_weather/items', value={'kind': 'Unknown', 'value': 'Winterjacke'}, slot_name='item', raw_value='winterjacke', confidence=1.0, range=SlotRange(start=22, end=33, raw_start=22, raw_end=33))], session_id='e6a3cfb7-98a2-47fd-b868-8401c1fadead', custom_data=None, asr_tokens=[[AsrToken(value='brauche', confidence=1.0, range_start=0, range_end=7, time=None), AsrToken(value='ich', confidence=1.0, range_start=8, range_end=11, time=None), AsrToken(value='heute', confidence=1.0, range_start=12, range_end=17, time=None), AsrToken(value='ein', confidence=1.0, range_start=18, range_end=21, time=None), AsrToken(value='Winterjacke', confidence=1.0, range_start=22, range_end=33, time=None)]], asr_confidence=None, raw_input='brauche ich heute ein winterjacke', wakeword_id=None, lang=None)`

**Comment by Daenara** [comment]
Let's see if I can do anything to help you.

First, it seems I need to link an example for rhasspy-hermes-app somewhere in the documentation, you are not the first person struggling with getting that to work. [Here](https://github.com/Daenara/MQTTSkillListener/blob/master/SkillListener.py) you cant take a look at how I run it, but it contains more than rhasspy_weather. Having that linked in the documentation or at least a more complete rhasspy_weather part of that script somewhere in there might help ppl out. I don't want to make step by step instructions on how to write a hermes-mqtt-skill listener and then run it (via docker, venv, systemd or the other thousands of ways there are) because that frankly isn't what rhasspy_weather is about but supplying an example script and telling ppl to run that seems to be something I have to do.

As for the value errors. They most likely are the result of your input being in a different format than the parser expects. Where did you get your input? Rhasspy itself is capable of different input formats, the one it displays on console for the inbuilt console scripts differs from the mqtt format, and there might even be formats that I did not run into yet (like the web api format). Those different formats are a bit unfortunate, because a one can read all solution is not viable with that. Also, your input seems to be missing a bit at the beginning. It ends on a closing round bracket that never opens which makes it hard to know if only this bracket is missing or more. 

With a full input and the knowledge of how you came to that input, I can test if this is a bug in the existing input parsers (because something changed or I did not test something as throughout as I should have) or if it is a completely new kind of input that is not supported by the current parsers. If it turns out it needs a new parser, then it depends on where the input came from if I write a parser to handle it, if it is something rhasspy can produce on its own  I will because I aim to fully support rhasspy, if you came by it via a 3rd party solution like node red or something, then I won't write the parser because it would set a bad precedent (I don't want to end up writing parsers for every imaginable szenario ppl could come up with, especially if they have nothing to do with rhasspy in the end or are unique to one person) but I can help you out by answering any questions you might have for writing one for yourself. Parsers are basically just a python file in the write folder that has two predefined functions in it. The first is the one that does all the parsing and basically it is just a case of knowing the input format and putting the right parts of the input format into the internal format I use to cope with all the different formats inputs can have.

EDIT: After looking over your input data, it looks similar to what rhasspy_hermes_app uses. Did you set the parser to "nlu_intent"? It might just be that you didn't change the parser/didn't make a config file or the config file is not found. It would help if you told me more about your setup, how you build your service, which python version it runs on, what your config looks like, and if you have them, log files. The more information you can give me, the easier it will be for me to help.

**Comment by ThisisDennis** [comment]
Oh my ...
You are right, i missed that nlu_intent part. Sorry for wasting your time and thank you very much for your help and your great work!
