### ISSUE TITLE
Weird output for temperature question in english

### ISSUE THREAD

**Issue by mots** [Daenara/rhasspy_weather#15]
Hey there! Looks like there's something wonky with the temperature output:

[INFO:2021-10-11 01:02:32,889] rhasspy_weather.output.log: {"intent": {"name": "GetWeatherForecastTemperature", "confidence": 1.0}, "entities": [{"entity": "temperature", "value": "warm", "value_details": {"kind": "Unknown", "value": "warm"}, "raw_value": "warm", "start": 18, "end": 22, "raw_start": 18, "raw_end": 22}, {"entity": "when_day", "value": "tomorrow", "value_details": {"kind": "Unknown", "value": "tomorrow"}, "raw_value": "tomorrow", "start": 23, "end": 31, "raw_start": 23, "raw_end": 31}, {"entity": "when_time", "value": "now", "value_details": {"kind": "Unknown", "value": "now"}, "raw_value": "now", "start": 32, "end": 35, "raw_start": 32, "raw_end": 35}], "slots": {"temperature": "warm", "when_day": "tomorrow", "when_time": "now"}, "text": "is it going to be warm tomorrow now", "raw_text": "is it going to be warm tomorrow now", "tokens": ["is", "it", "going", "to", "be", "warm", "tomorrow", "now"], "raw_tokens": ["is", "it", "going", "to", "be", "warm", "tomorrow", "now"], "wakeword_id": "computer_raspberry-pi", "speech": {"text": "No, tomorrow now will not be warm. The temperature will be {temperature}. The temperature is 17 degrees."}}

> No, tomorrow now will not be warm. The temperature will be {temperature}. The temperature is 17 degrees

**Comment by Daenara** [comment]
Evening, thanks for catching that.

The first weird thing about that sentence is something I can't do much about, the whole program is mostly tuned for times in the format day and month plus time and today/tomorrow plus time. "now" is only supposed to replace that whole construct, so I don't have any cases that fit for tomorrow plus now, I'm not even sure for when exactly it will fetch the weather, hopefully for tomorrow at the same time it is now. 

The 2nd part was me not removing the temperature part from one sentence part after I moved it to another. I only use this in German, so English gets translated by me, but not tested since all the testing I do is done via rhasspy and mine doesn't speak English and I doubt it would understand my accent. I fixed that now. 

Also, if you want to change sentences around because my grammar is bad, or if you want to add to the sentences, there is an english.py file in the language folder that defines all the sentence parts that will be used by rhasspy_weather. In theory rhasspy_weather takes a random sentence part for whatever it needs from the list and then fills in the bracketed stuff with values.  Practically most English sentence parts only have one possibility because my English is not good enough to write sentences that are used and still don't sound strange once they are combined with other parts. This file is also the one you add in new items for weather conditions as well as synonyms for times of day, days, etc. I filled all off it out but if you think you can improve on it, go for it, I know my English language file is not the best out there.
